version: "3.3"
services:
  redis:
    image: redisuniversity/ru202-lab
    ports:
      - "8888:8888"
      - "6379:6379"
    container_name: redis_lab
    networks:
      - redis-network

# docker run -it --network redis-net --rm redis redis-cli -h redis-server