version: "3.8"
services:
  redis:
    image: redisuniversity/ru202-lab
    ports:
      - "8888:8888"
      - "6379:6379"
    container_name: redis_lab
    networks:
      redis:

networks:
  redis:
    name: stream

# docker run -it --network stream --rm redis redis-cli -h redis_lab